
title: Resume
url: 'http://junlulocky.com'
baseurl: '/sanjastanisic.github.io' #change it according to your repository name



# Profile information
yourname: Sanja Stanišić
title: 'PR &amp; Project Manager'  
location: Belgrade, Serbia


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/sanja-stanisic-803ba61b/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
